Final App/src/main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView
from . import views

app_name = 'main'
urlpatterns = [
    #path('', views.index, name='index'),
    path('', RedirectView.as_view(url='/service/', permanent=True), name="index"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('service/', include('service.urls')),
    path('settings/', views.settings, name='settings'),
    path('notifications/', views.get_notifications, name='notifications'),
    path('notifications/<int:notif_id>/read', views.mark_notification_read, name='read-notification'), 
    path('notifications/all/read', views.markall_notification_read, name='read-notification-all'),
] 

Final App/src/service/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'service'  # SET THE NAMESPACE!
urlpatterns = [
    path('', views.index, name='index'),
    path('explore/', views.explore, name='explore'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('detail/<int:post_id>', views.detail, name='detail'),
    path('update/<int:post_id>', views.update, name='update'),
    path('close/<int:post_id>', views.close, name='close'), 
    path('delete/<int:post_id>', views.delete, name='delete'),

    path('<int:post_id>/comment/create/', views.create_comment, name='create-comment'),
]

Final App/src/user/urls.py
from django.urls import path
from . import views

app_name = 'user'  # SET THE NAMESPACE!
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('info/', views.info, name='info'),
    path('activity/', views.activity, name='activity'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_id>', views.data, name='data'),    
]

crse/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from crossservice import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^cross/', include('crossservice.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

Final App/src/main/models.py
from django.db import models

Final App/src/user/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

class Profile(models.Model):
    class Meta:
        app_label = 'user'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    bio = models.TextField(max_length=200, blank=True)

    phone = models.CharField(max_length=20, help_text='Enter phone number.')
    address = models.CharField(max_length=100, help_text='Enter address.')

    available = models.BooleanField(default=False)

    def email(self):
        return self.user.username
        
    def __str__(self):
        return self.user.username

Final App/src/main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, Http404

from django.urls import reverse
from django.contrib import auth, messages

from service.models import Notification

@login_required
def settings(request):
    return render(request, 'main/settings.html', context={
        'navigation': 'settings',
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })

@login_required
def get_notifications(request):
    
    try:
        notifications = Notification.objects.filter(
            owner=request.user
        ).order_by('-created_datetime')
    except Notification.DoesNotExist:
        notifications = []

    return render(request, 'main/notifications.html', context={
        'navigation': 'notifications',
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count(),
        'notifications': notifications,
    })


@login_required
def mark_notification_read(request, notif_id):
    try:
        notification = Notification.objects.filter(
            pk=notif_id
        )
    except Notification.DoesNotExist:
        raise Http404('Notification does not exist!')
    
    notification.is_read = True
    notification.save()

    messages.success(request, "Notification marked read!" , extra_tags='message-head info')
    messages.success(request, "You've successfully marked a notification as read.", extra_tags="message-body")

    return HttpResponseRedirect(reverse('notifications'))


@login_required
def markall_notification_read(request):
    try:
        unread = Notification.objects.filter(
            is_read=False
        )
    except Notification.DoesNotExist:
        raise Http404('Notification does not exist!')
    
    for notification in unread:
        notification.is_read = True
        notification.save()
    
    messages.success(request, "All unread notifications marked read!" , extra_tags='message-head info')
    messages.success(request, "You've successfully marked all unread notifications as read.", extra_tags="message-body")

    return HttpResponseRedirect(reverse('notifications'))

    

Final App/src/service/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse

from django.contrib import messages
import datetime

from django.db.models import Q
from .models import *


@login_required
def index(request):
    service_posts = ServicePost.objects.filter().order_by('-created_datetime')[:10]
    
    return render(request, 'service/index.html', {
        'navigation': 'service',
        'service_posts': service_posts,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })


@login_required
def explore(request):
    service_posts = ServicePost.objects.filter().order_by('-created_datetime')
    return render(request, 'service/explore.html', {
        'navigation': 'service',
        'service_posts': service_posts,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })        


@login_required
def search(request):
    
    if request.method == 'GET':
        search_text = request.GET.get('service_search_text')

        title_matches = ServicePost.objects.filter(
            Q(title__icontains=search_text) | Q(service__name__icontains=search_text)
        )

        description_matches = ServicePost.objects.filter(
            Q(description__icontains=search_text) | Q(service__info__icontains=search_text)
        )

        location_matches = ServicePost.objects.filter(
            Q(service__location__icontains=search_text)
        )

        tag_matches = ServicePost.objects.filter(
            
        ).filter(service__tags__label__icontains=search_text)
         

    return render(request, 'service/search.html', {
        'search_text': search_text,
        'navigation': 'service',
        'title_matches': title_matches,
        'description_matches': description_matches,
        'location_matches': location_matches,
        'tag_matches': tag_matches,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })


@login_required
def create(request):
    if request.method == 'POST':
        # Creating new service and saving it
        new_service = Service()
        new_service.name = request.POST.get('service-name')
        new_service.info = request.POST.get('service-description')
        new_service.start_datetime = request.POST.get('service-start-datetime')
        new_service.end_datetime = request.POST.get('service-end-datetime')
        new_service.location = request.POST.get('service-location')
        
        new_service.save() 
        tags = request.POST.getlist('service-tags')
        for tag_name in tags:
            tag, created = Tag.objects.get_or_create(
                label = tag_name
            )
            
            new_service.tags.add(tag)
        
        new_service.save()

        # Creating new service post record and saving it
        new_post = ServicePost()
        new_post.title = request.POST.get('post-title')
        new_post.description= request.POST.get('post-description')
        new_post.is_request_post = (request.POST['is_request_post'] == '1')
        new_post.owner = User.objects.get(username=request.user.username)
        new_post.created_datetime = datetime.datetime.now()
        new_post.service = new_service
        
        new_post.save()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You created a new service post titled '" + request.POST.get('post-title') + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post Published!", extra_tags='message-head')
        
        messages.success(request, 'Hey ' + request.user.first_name + '! We have recorded and published your post!', extra_tags="message-body")
        
        return HttpResponseRedirect(reverse('service:create'))
    
    return render(request, 'service/create.html', {
        'navigation': 'service',
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })
    
@login_required
def detail(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
        comments = ServicePostComment.objects.filter(post=post).order_by('-created_datetime')

    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    return render(request, 'service/details.html', {
        'navigation': 'service',
        'post': post,
        'comments': comments,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })


@login_required
def update(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.method == 'POST':
        
        post.service.name = request.POST.get('service-name')
        post.service.info = request.POST.get('service-description')
        post.service.start_datetime = request.POST.get('service-start-datetime')
        post.service.end_datetime = request.POST.get('service-end-datetime')
        post.service.location = request.POST.get('service-location')
        
        post.service.save()
        post.save()

        post.service.tags.clear()
        tags = request.POST.getlist('service-tags')
        for tag_name in tags:
            tag, created = Tag.objects.get_or_create(
                label = tag_name
            )
            
            post.service.tags.add(tag)
        
        post.service.save()
        post.save()

        post.title = request.POST.get('post-title')
        post.description= request.POST.get('post-description')
        post.is_request_post = (request.POST['is_request_post'] == '1')
        post.modified_datetime = datetime.datetime.now()
        
        post.save()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You updated your service post information. The post is titled '" + request.POST.get('post-title') + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post Updated!", extra_tags='message-head')
        
        messages.success(request, 'Hey ' + request.user.first_name + '! We have updated your post!', extra_tags="message-body")
        
        return HttpResponseRedirect(reverse('service:update', kwargs={'post_id': post.id})) 
    
    return render(request, 'service/update.html', {
        'navigation': 'service',
        'post': post,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })

@login_required
def close(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.user != post.owner:
        messages.warning(request, "Unauthorized Attempt", extra_tags='message-head')
        messages.warning(request, "You're not authorized to perform this operation. Only the post owner can close the post.", extra_tags='message-body')

    else:
        post.closed_datetime = datetime.datetime.now()
        post.save()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You recently closed a service post titled '" + post.title + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post closed", extra_tags='message-head info')
        messages.warning(request, "You've recently closed a service post. You will no require receive comments in that post, although the post is still visible unless you delete it!", extra_tags='message-body')

    return HttpResponseRedirect(reverse('service:detail', kwargs={'post_id': post.id}))


@login_required
def delete(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.user != post.owner:
        messages.warning(request, "Unauthorized Attempt", extra_tags='message-head error')
        messages.warning(request, "You're not authorized to perform this operation. Only the post owner can delete the post.", extra_tags='message-body')

    else:
        post.service.delete()
        post.delete()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You deleted your service post titled '" + post.title + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post Deleted", extra_tags='message-head info')
        messages.warning(request, "You've successfully deleted a service post. You will no longer be able to access the post!", extra_tags='message-body')

    return HttpResponseRedirect(reverse('service:index'))


@login_required
def create_comment(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.method == 'POST':
        comment_text = request.POST.get('comment')
        
        new_comment = ServicePostComment()
        new_comment.text = comment_text
        new_comment.created_datetime = datetime.datetime.now()

        new_comment.owner = request.user
        new_comment.post = post

        new_comment.is_private = False
        if request.POST.get('is-private'):

Final App/src/templates/base_generic.html
<!DOCTYPE html>
<html lang="en" class="{% if messages %}is-clipped{% endif %}">
<head>
  <title>{% block title-main %}Explore Services{% endblock %} | Cross Service</title>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css" />

  
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous" />
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <script src="{% static 'js/main.js' %}" defer></script>
  
</head>

<body class="has-navbar-fixed-top ">

    <!-- Display any onload messages. -->
    {% if messages %}
    <div id="onload-modal" class="modal animated zoomIn is-active">
        <div class="modal-background" onclick=""></div>
        <div class="modal-card has-text-black">

        {% for message in messages %}
            {% if 'message-head' in message.tags %}
            <header class="modal-card-head {{ message.tags }} ">
                <p class="modal-card-title">{{ message }}</p>
                
                <p>
                    {% if 'success' in message.tags %}
                        <sup class="tag is-success">SUCCESS</sup>
                    {% endif %}
                    {% if 'error' in message.tags %}
                        <sup class="tag 
                        is-danger">ERROR</sup>
                    {% endif %}
                    {% if 'warning' in message.tags  %}
                        <sup class="tag is-warning">WARNING</sup>
                    {% endif %}
                    {% if 'info' in message.tags %}
                        <sup class="tag is-info">INFO</sup>
                    {% endif %}
                </p>

            </header>
            {% endif %}

            {% if 'message-body' in message.tags %}
            <section class="modal-card-body">
                {{ message }}
            </section>
            {% endif %}
        {% endfor %}

            <footer class="modal-card-foot">
                <button class="button is-link is-outlined" onclick="toggleModal(document.getElementById('onload-modal'));">Okay, Got it!</button>
            </footer>
        </div>
    </div>
    {% endif %}

    <!-- User Info Modal -->
    <div id="user-info-modal" class="modal animated fadeIn">
        <div class="modal-background" onclick="this.parentNode.classList.remove('is-active');"></div>

        <div class="modal-content box">
            <!-- Any other Bulma elements you want -->
            <div id="" class="">
                <fieldset class="m-t-sm" style="border-top: 1px solid #ccc;">
                    <legend class="subtitle is-5 has-text-centered has-text-weight-bold p-l-sm p-r-sm p-t-none">Basic Information</legend>
                    
                    <i class="is-pulled-right far fa-user-circle is-size-1"></i>
                    
                    <div>
                        <label class="label">Name: </label>
                        <span class="name subtitle"></span>
                    </div>

                    <div>
                        <label class="label">Bio: </label><span class="bio subtitle"></span>
                    </div>
                    
                    <div>
                        <label class="label">Currently Availabile: </label>
                        <span class="available subtitle"></span>
                    </div>
                    
                </fieldset>

                <fieldset class="m-t-lg" style="border-top: 1px solid #ccc;">
                    <legend class="subtitle is-5 has-text-centered has-text-weight-bold p-l-sm p-r-sm">Contact Details</legend>

                    <div>
                        <label class="label">Email: </label>
                        <span class="email subtitle"></span>
                    </div>

                    <div>
                        <label class="label">Phone: </label>
                        <span class="phone subtitle"></span>
                    </div>

                    <div>
                        <label class="label">Address: </label>
                        <span class="address subtitle"></span>
                    </div>
                </fieldset>
            </div>
        </div>

        <button class="modal-close is-large" aria-label="close" onclick="this.parentNode.classList.remove('is-active');"></button>
    </div>

    <nav id="fixed-topbar" class="navbar is-fixed-top has-background-white-info p-xs" role="navigation" aria-label="main navigation">
        <div class="navbar-brand has-text-centered p-l-lg" style="width:100%;">
            <a class="navbar-item has-poppins-text is-size-4 has-text-weight-semibold "  href="/service">
                Cross Service
            </a>
            
            <div class="navbar-end level is-mobile" style="width:100%;">
                <div class="level-left"></div>
                <div class="level-right has-text-right">
                    {% if user.is_authenticated %}
                    <a href="{% url 'user:info' %}" class="level-item is-hidden-mobile navbar-item has-icons-left">
                        <span class="icon">
                            <i class="fas fa-user-circle"></i>
                        </span>&nbsp;{{ user.username }}
                    </a>
            
                    <div class="level-item ">
                        <a class="button is-link is-outlined has-text-weight-semibold m-r-sm" style="font-size: 0.8rem;" href="{% url 'user:logout' %}">
                            <span class="icon is-size-6">
                                <i class="fas fa-sign-out-alt"></i>
                            </span>
                            &nbsp; LOG OUT
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>

        </div>
    
    </nav>


    <div class="body-content columns is-gapless" style="padding: 1.5rem; min-height: calc(100vh - 3.25rem);">
        
        <div class="column is-narrow " style="width: 220px;">

            <nav class="panel has-background-white sticky-sidebar" >
                
                <p class=" panel-heading has-text-centered has-background-white-ter has-text-weight-semibold">
                    Navigation
                </p>

                {% if user.is_authenticated %}
                <a class="panel-block {% if 'service' in navigation %}is-active has-text-weight-semibold{% endif %}" href="{% url 'service:index' %}">
                    <span class="panel-icon">
                        <i class="fab fa-servicestack" aria-hidden="true"></i>
                    </span>
                    Services
                </a>
				
				<a class="panel-block {% if 'notifications' in navigation %}is-active has-text-weight-semibold{% endif %}" href="{% url 'notifications' %}" title="{% if unread_notifications_count > 0 %}{{unread_notifications_count}}{% else %}0{% endif %} unread notifications!">
                    <span class="panel-icon">
                        <i class="fas fa-bell" aria-hidden="true"></i>
                    </span>
                    Notifications &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    
                    <span class="tag {% if unread_notifications_count > 0 %}is-link {% else %} is-light {% endif %} has-text-weight-semibold is-normal is-rounded" title="">
                        {% if unread_notifications_count > 0 %}{{unread_notifications_count}}{% else %}0{% endif %}
                    </span>
                    
                </a>

                <a class="panel-block {% if 'profile' in navigation %}is-active has-text-weight-semibold{% endif %}" href="{% url 'user:info' %}">
                    <span class="panel-icon">
                        <i class="fas fa-user-cog" aria-hidden="true"></i>
                    </span>
                    My Profile
                </a>

                <a class="panel-block {% if 'settings' in navigation %}is-active has-text-weight-semibold{% endif %}" href="{% url 'settings' %}">
                    <span class="panel-icon">
                        <i class="fas fa-cog" aria-hidden="true"></i>
                    </span>
                    Settings
                </a>
                {% else %}
                <a class="panel-block {% if 'login' in navigation %}is-active has-text-weight-semibold{% endif %}" href="{% url 'user:login' %}">
                    <span class="panel-icon">
                        <i class="fas fa-sign-in-alt" aria-hidden="true"></i>
                    </span>
                    Login
                </a>

                <a class="panel-block {% if 'register' in navigation %}is-active has-text-weight-semibold{% endif %}" href="{% url 'user:register' %}">
                    <span class="panel-icon">
                        <i class="fas fa-id-card" aria-hidden="true"></i>
                    </span>
                    Register
                </a>

                {% endif %}
                
            </nav>

            

        </div>
        

        <div class="column animated slideInDown">
            <div class="p-lg">
                {% block page-content %}{% endblock %}            
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
</body>
</html>