Final App/src/main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView
from . import views

app_name = 'main'
urlpatterns = [
    #path('', views.index, name='index'),
    path('', RedirectView.as_view(url='/service/', permanent=True), name="index"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('service/', include('service.urls')),
    path('settings/', views.settings, name='settings'),
    path('notifications/', views.get_notifications, name='notifications'),
    path('notifications/<int:notif_id>/read', views.mark_notification_read, name='read-notification'), 
    path('notifications/all/read', views.markall_notification_read, name='read-notification-all'),
] 

crossservice/urls.py
from django.conf.urls import url
from django.urls import path

from crossservice import views

# SET THE NAMESPACE!
app_name = 'crossservice'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^delete_account/$', views.user_delete, name='user_delete'),
    url(r'^update_account/$', views.user_update, name='user_update'),
    url(r'^post_service/$', views.post_service, name='post'),
    url(r'^delete_post/$', views.remove_service_post, name='post_delete'),
    url(r'^update_post/$', views.update_service_post, name='post_update'),
    path('posts/', views.listPosts.as_view(), name='posts'),
]

crse/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from crossservice import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^cross/', include('crossservice.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Cross Service</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          {% if not user.is_authenticated %}<li><a class="navbar-link" href="{% url 'crossservice:register' %}">Register</a></li> {% endif %}
            {% if user.is_authenticated %}<li><a class="navbar-link" href="{% url 'crossservice:dashboard' %}">Dashboard</a></li> {% endif %}
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'crossservice:user_login' %}">Login</a></li>
          {% endif %}

</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% block body_block %}
    Username: {{ username }} <br>
    {% for i in info %}
        Location: {{ i.location }} <br>
        Bio: {{ i.bio }} <br>
        Org: {{ i.organization }} <br>
    {% endfor %}
    <a class="navbar-brand" href="{% url 'crossservice:user_delete' %}">Delete Account</a>
    <a class="navbar-brand" href="{% url 'crossservice:user_update' %}">Update Account</a><br>
    <a class="navbar-brand" href="{% url 'crossservice:post' %}">Post</a><br>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Cross Service !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
    <a class="navbar-brand" href="{% url 'crossservice:posts' %}">Posts</a><br>
  </div>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>

<form method="post" action="{% url 'crossservice:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">

<input type="submit" name="" value="Login">

</form>

</div>
  </div>
{% endblock %}

templates/post_service.html
{% extends "base.html" %}
{% block body_block %}
<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">POST!</button>
</form>
{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}

templates/update.html
{% extends "base.html" %}
{% block body_block %}
<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Profile</button>
</form>
{% endblock %}