Final App/src/main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView
from . import views

app_name = 'main'
urlpatterns = [
    #path('', views.index, name='index'),
    path('', RedirectView.as_view(url='/service/', permanent=True), name="index"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('service/', include('service.urls')),
    path('settings/', views.settings, name='settings'),
    path('notifications/', views.get_notifications, name='notifications'),
    path('notifications/<int:notif_id>/read', views.mark_notification_read, name='read-notification'), 
    path('notifications/all/read', views.markall_notification_read, name='read-notification-all'),
] 

Final App/src/service/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'service'  # SET THE NAMESPACE!
urlpatterns = [
    path('', views.index, name='index'),
    path('explore/', views.explore, name='explore'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('detail/<int:post_id>', views.detail, name='detail'),
    path('update/<int:post_id>', views.update, name='update'),
    path('close/<int:post_id>', views.close, name='close'), 
    path('delete/<int:post_id>', views.delete, name='delete'),

    path('<int:post_id>/comment/create/', views.create_comment, name='create-comment'),
]

Final App/src/user/urls.py
from django.urls import path
from . import views

app_name = 'user'  # SET THE NAMESPACE!
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('info/', views.info, name='info'),
    path('activity/', views.activity, name='activity'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_id>', views.data, name='data'),    
]

crse/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from crossservice import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^cross/', include('crossservice.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

Final App/src/main/models.py
from django.db import models

Final App/src/user/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

class Profile(models.Model):
    class Meta:
        app_label = 'user'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    bio = models.TextField(max_length=200, blank=True)

    phone = models.CharField(max_length=20, help_text='Enter phone number.')
    address = models.CharField(max_length=100, help_text='Enter address.')

    available = models.BooleanField(default=False)

    def email(self):
        return self.user.username
        
    def __str__(self):
        return self.user.username

Final App/src/main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, Http404

from django.urls import reverse
from django.contrib import auth, messages

from service.models import Notification

@login_required
def settings(request):
    return render(request, 'main/settings.html', context={
        'navigation': 'settings',
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })

@login_required
def get_notifications(request):
    
    try:
        notifications = Notification.objects.filter(
            owner=request.user
        ).order_by('-created_datetime')
    except Notification.DoesNotExist:
        notifications = []

    return render(request, 'main/notifications.html', context={
        'navigation': 'notifications',
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count(),
        'notifications': notifications,
    })


@login_required
def mark_notification_read(request, notif_id):
    try:
        notification = Notification.objects.filter(
            pk=notif_id
        )
    except Notification.DoesNotExist:
        raise Http404('Notification does not exist!')
    
    notification.is_read = True
    notification.save()

    messages.success(request, "Notification marked read!" , extra_tags='message-head info')
    messages.success(request, "You've successfully marked a notification as read.", extra_tags="message-body")

    return HttpResponseRedirect(reverse('notifications'))


@login_required
def markall_notification_read(request):
    try:
        unread = Notification.objects.filter(
            is_read=False
        )
    except Notification.DoesNotExist:
        raise Http404('Notification does not exist!')
    
    for notification in unread:
        notification.is_read = True
        notification.save()
    
    messages.success(request, "All unread notifications marked read!" , extra_tags='message-head info')
    messages.success(request, "You've successfully marked all unread notifications as read.", extra_tags="message-body")

    return HttpResponseRedirect(reverse('notifications'))

    

Final App/src/service/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse

from django.contrib import messages
import datetime

from django.db.models import Q
from .models import *


@login_required
def index(request):
    service_posts = ServicePost.objects.filter().order_by('-created_datetime')[:10]
    
    return render(request, 'service/index.html', {
        'navigation': 'service',
        'service_posts': service_posts,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })


@login_required
def explore(request):
    service_posts = ServicePost.objects.filter().order_by('-created_datetime')
    return render(request, 'service/explore.html', {
        'navigation': 'service',
        'service_posts': service_posts,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })        


@login_required
def search(request):
    
    if request.method == 'GET':
        search_text = request.GET.get('service_search_text')

        title_matches = ServicePost.objects.filter(
            Q(title__icontains=search_text) | Q(service__name__icontains=search_text)
        )

        description_matches = ServicePost.objects.filter(
            Q(description__icontains=search_text) | Q(service__info__icontains=search_text)
        )

        location_matches = ServicePost.objects.filter(
            Q(service__location__icontains=search_text)
        )

        tag_matches = ServicePost.objects.filter(
            
        ).filter(service__tags__label__icontains=search_text)
         

    return render(request, 'service/search.html', {
        'search_text': search_text,
        'navigation': 'service',
        'title_matches': title_matches,
        'description_matches': description_matches,
        'location_matches': location_matches,
        'tag_matches': tag_matches,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })


@login_required
def create(request):
    if request.method == 'POST':
        # Creating new service and saving it
        new_service = Service()
        new_service.name = request.POST.get('service-name')
        new_service.info = request.POST.get('service-description')
        new_service.start_datetime = request.POST.get('service-start-datetime')
        new_service.end_datetime = request.POST.get('service-end-datetime')
        new_service.location = request.POST.get('service-location')
        
        new_service.save() 
        tags = request.POST.getlist('service-tags')
        for tag_name in tags:
            tag, created = Tag.objects.get_or_create(
                label = tag_name
            )
            
            new_service.tags.add(tag)
        
        new_service.save()

        # Creating new service post record and saving it
        new_post = ServicePost()
        new_post.title = request.POST.get('post-title')
        new_post.description= request.POST.get('post-description')
        new_post.is_request_post = (request.POST['is_request_post'] == '1')
        new_post.owner = User.objects.get(username=request.user.username)
        new_post.created_datetime = datetime.datetime.now()
        new_post.service = new_service
        
        new_post.save()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You created a new service post titled '" + request.POST.get('post-title') + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post Published!", extra_tags='message-head')
        
        messages.success(request, 'Hey ' + request.user.first_name + '! We have recorded and published your post!', extra_tags="message-body")
        
        return HttpResponseRedirect(reverse('service:create'))
    
    return render(request, 'service/create.html', {
        'navigation': 'service',
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })
    
@login_required
def detail(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
        comments = ServicePostComment.objects.filter(post=post).order_by('-created_datetime')

    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    return render(request, 'service/details.html', {
        'navigation': 'service',
        'post': post,
        'comments': comments,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })


@login_required
def update(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.method == 'POST':
        
        post.service.name = request.POST.get('service-name')
        post.service.info = request.POST.get('service-description')
        post.service.start_datetime = request.POST.get('service-start-datetime')
        post.service.end_datetime = request.POST.get('service-end-datetime')
        post.service.location = request.POST.get('service-location')
        
        post.service.save()
        post.save()

        post.service.tags.clear()
        tags = request.POST.getlist('service-tags')
        for tag_name in tags:
            tag, created = Tag.objects.get_or_create(
                label = tag_name
            )
            
            post.service.tags.add(tag)
        
        post.service.save()
        post.save()

        post.title = request.POST.get('post-title')
        post.description= request.POST.get('post-description')
        post.is_request_post = (request.POST['is_request_post'] == '1')
        post.modified_datetime = datetime.datetime.now()
        
        post.save()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You updated your service post information. The post is titled '" + request.POST.get('post-title') + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post Updated!", extra_tags='message-head')
        
        messages.success(request, 'Hey ' + request.user.first_name + '! We have updated your post!', extra_tags="message-body")
        
        return HttpResponseRedirect(reverse('service:update', kwargs={'post_id': post.id})) 
    
    return render(request, 'service/update.html', {
        'navigation': 'service',
        'post': post,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })

@login_required
def close(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.user != post.owner:
        messages.warning(request, "Unauthorized Attempt", extra_tags='message-head')
        messages.warning(request, "You're not authorized to perform this operation. Only the post owner can close the post.", extra_tags='message-body')

    else:
        post.closed_datetime = datetime.datetime.now()
        post.save()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You recently closed a service post titled '" + post.title + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post closed", extra_tags='message-head info')
        messages.warning(request, "You've recently closed a service post. You will no require receive comments in that post, although the post is still visible unless you delete it!", extra_tags='message-body')

    return HttpResponseRedirect(reverse('service:detail', kwargs={'post_id': post.id}))


@login_required
def delete(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.user != post.owner:
        messages.warning(request, "Unauthorized Attempt", extra_tags='message-head error')
        messages.warning(request, "You're not authorized to perform this operation. Only the post owner can delete the post.", extra_tags='message-body')

    else:
        post.service.delete()
        post.delete()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You deleted your service post titled '" + post.title + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post Deleted", extra_tags='message-head info')
        messages.warning(request, "You've successfully deleted a service post. You will no longer be able to access the post!", extra_tags='message-body')

    return HttpResponseRedirect(reverse('service:index'))


@login_required
def create_comment(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.method == 'POST':
        comment_text = request.POST.get('comment')
        
        new_comment = ServicePostComment()
        new_comment.text = comment_text
        new_comment.created_datetime = datetime.datetime.now()

        new_comment.owner = request.user
        new_comment.post = post

        new_comment.is_private = False
        if request.POST.get('is-private'):

Final App/src/templates/user/logged_out.html
{% extends "../base_generic.html" %}

{% block title-main %}Logged out{% endblock %}

{% block page-content %}
    <p class="notification is-white">
        You have been successfully logged out of the system. To continue using our services,
        <a class="is-link" href="{% url 'user:login' %}">login</a> again.
    </p>
{% endblock %}

Final App/src/templates/user/login.html
{% extends "../base_generic.html" %}

{% block title-main %}Login{% endblock %}

{% block page-content %}
    {% load static %}
    <script src="{% static 'js/user.js' %}" defer></script>

    {% if form.errors %}
        <p class="notification is-warning">
            <button class="delete"></button>
            Your username and password didn't match. Please try again.
        </p>
    {% else %}
        {% if next %}
            {% if user.is_authenticated %}
                <p class="notification is-warning">
                    Your account doesn't have access to this page. To proceed,
                    please login with an account that has access.
                </p>
            {% else %}
                <div class="notification is-info">
                    <button class="delete"></button>
                    Please login first. You'll then be automatically taken to the requested page.
                </div>
            {% endif %}
        {% endif %}
    {% endif %}

    <form id="login-form" class="box center-h p-lg" method="post" action="{% url 'user:login' %}" style="max-width: 380px; ">
        {% csrf_token %}
    
        <div class="title is-4 has-text-centered p-md">
            Member Login
        </div>

        <div class="field has-text-centered">
            <i class="far fa-user-circle is-size-1"></i>
        </div>

        <div class="field">
            <label class="label" for="{{ form.username.label }}">Email</label>
            <div class="control has-icons-left">
                <input class="input" type="email" name="username" placeholder="you@example.com" value="" required />
                <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                </span>
            </div>
        </div>
              
        <div class="field">
            <label class="label" for="{{ form.password.label }}">Password</label>
            <div class="control has-icons-left">
                <input class="input" type="password" name="password" placeholder="xxxxxxxxxxx" value="" required />
                <span class="icon is-small is-left">
                    <i class="fas fa-key"></i>
                </span>
            </div>
        </div>

        {# Assumes you setup the password_reset view in your URLconf #}

        <p class="field">
            <a href="#">Lost password?</a>
        </p>

        <div class="field is-grouped m-t-md m-b-lg">
            <div class="control">
                <input type="submit" class="button is-link p-l-xl p-r-xl " value="Login" />
            </div>
            <div class="control">
                <button class="button m-l-lg p-l-lg p-r-lg is-dark" onclick="clearLoginForm();">Clear</button>
            </div>
        </div>

        <div class="field p-t-sm">
            Not a member yet? <a class="is-text" href="{% url 'user:register' %}">Register an account</a> first.
        </div>

        <input type="hidden" name="next" value="{{ next }}" />
    </form>

{% endblock %}

Final App/src/templates/user/profile.html
{% extends "../base_generic.html" %}

{% block title-main %}Profile{% endblock %}

{% block page-content %}
    {% load static %}
    <script src="{% static 'js/user.js' %}" defer></script>
    
    <div class="tabs is-centered is-toggle is-toggle-rounded">
        <ul>
            <li class="{% if 'activity' in request.resolver_match.url_name %}is-active{% endif %}">
                <a id="profile-activity" href="{% url 'user:activity' %}">
                    <span class="icon is-small"><i class="fas fa-stream" aria-hidden="true"></i></span>
                    <span>Profile Activity</span>
                </a>
            </li>
    
            <li class="{% if 'info' in request.resolver_match.url_name %}is-active{% endif %}">
                <a id="profile-view" href="{% url 'user:info' %}">
                    <span class="icon is-small"><i class="far fa-user" aria-hidden="true"></i></span>
                    <span>View Profile</span>
                </a>
            </li>

            <li class="{% if 'update' in request.resolver_match.url_name %}is-active{% endif %}">
                <a id="profile-update" href="{% url 'user:update' %}">
                    <span class="icon is-small"><i class="fas fa-user-edit" aria-hidden="true"></i></span>
                    <span>Update Profile</span>
                </a>
            </li>
        </ul>
    </div>

    {% if 'activity' in request.resolver_match.url_name %}
    <div id="profile-activity-content" class="">
        <div class="subtitle has-text-centered is-size-5 p-sm">
            Your profile activity is a <span class="is-underlined">summary of service request/offering posts</span> you made so far!
        </div>

            {% for post in posts %}
            <fieldset class="m-t-lg" style="border-top: 1px solid #ccc;">
        
                <legend class="subtitle is-6 has-text-centered has-text-weight-bold p-l-sm p-r-sm">{{ post.created_datetime }}</legend>

                <div class="box" style="">
                    <div class="title is-5 has-text-grey-dark" style="height: 24px; overflow: hidden; text-overflow: ellipsis;">
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.title }}
                        </a>
                    </div>
                    <div class="" style="height: 48px; overflow:hidden; text-overflow:ellipsis;">
                        {{ post.description }}
                    </div>
                </div>
        
            </fieldset>
            {% endfor %}
      
    </div>
    {% endif %}

    {% if 'info' in request.resolver_match.url_name %}
    <div id="profile-view-content" class="">
        <fieldset class="m-t-lg" style="border-top: 1px solid #ccc;">
            <legend class="subtitle is-5 has-text-centered has-text-weight-bold p-l-sm p-r-sm p-t-none">Basic Information</legend>
            
            <i class="is-pulled-right far fa-user-circle is-size-1"></i>
            
            <div>
                <label class="label">Name: </label>{{ user.first_name }} {{ user.last_name }}
            </div>

            <div>
                <label class="label">Bio: </label>{{ user.profile.bio }}
            </div>
            
            <div>
                <label class="label">Currently Availabile: </label>
                {% if user.profile.available %}Yes{% else %}No{% endif %}
            </div>
            
        </fieldset>

        <fieldset class="m-t-lg" style="border-top: 1px solid #ccc;">
            <legend class="subtitle is-5 has-text-centered has-text-weight-bold p-l-sm p-r-sm">Contact Details</legend>

            <div>
                <label class="label">Email: </label>{{ user.username }}
            </div>

            <div>
                <label class="label">Phone: </label>{{ user.profile.phone }}
            </div>

            <div>
                <label class="label">Address: </label>{{ user.profile.address }}
            </div>
        </fieldset>

    </div>
    {% endif %}

    {% if 'update' in request.resolver_match.url_name %}
    <div id="profile-update-content" class="">
    <form id="update-form" method="post" action="{% url 'user:update' %}" class="box center-h p-lg" style="max-width: 700px;">
        {% csrf_token %}

        <div class="field title is-4 has-text-centered p-md">
            Profile Update Form
        </div>

        <div class="columns m-t-md">
            <div class="column is-half">
                <div class="field">
                    <label class="label">First Name</label>
                    <div class="control">
                        <input type="text" class="input" name="first_name" placeholder="John" value="{{ user.first_name }}" required />
                    </div>
                </div>

                <div class="field">
                    <label class="label">Last Name</label>
                    <div class="control">
                        <input type="text" class="input" name="last_name" placeholder="Doe" value="{{ user.last_name }}" required />
                    </div>
                </div>
                
                <div class="field">
                    <label class="label">Bio</label>
                    <div class="control">
                        <textarea class="input" name="bio" style="resize: vertical; min-height: 115px; max-height: 200px;">{{ user.profile.bio }}</textarea>
                    </div>
                </div>

                <div class="field">
                    <label class="label">Set Availability</label>
                    <div class="help">Are you currently available to provide services?</div>
                    
                    <input type="radio" name="available" value="1" {% if user.profile.available == 1 %}checked {% endif %} required /> Yes
                    <input type="radio" name="available" value="0" class="m-l-md" {% if user.profile.available == 0 %}checked {% endif %} required /> No
                </div>

            </div>

            <div class="column is-half">
                <div class="field">
                    <label class="label">Phone</label>
                    <div class="control">
                        <input type="tel" class="input" name="phone" placeholder="+7 (928) 9387 8219" value="{{ user.profile.phone }}"  />
                    </div>
                </div>
                               

                <div class="field">
                    <label class="label">Address</label>
                    <div class="control">
                        <input type="text" class="input" name="address" placeholder="Universitetskaya St 1, Innopolis, Tatarstan" value="{{ user.profile.address }}" />
                    </div>
                </div>

                <div class="field">
                    <label class="label">Email</label>
                    <div class="control">
                        <input type="email" class="input" name="username" placeholder="you@example.com" value="{{ user.username }}" required />
                    </div>
                </div>

                <div class="field">
                    <label class="label">New Password</label>
                    <div class="control">
                        <input type="password" class="input" name="confirm_password" />
                    </div>
                </div>

                <div class="field">
                    <label class="label">Confirm New Password</label>
                    <div class="control">
                        <input type="password" class="input" name="password" />
                    </div>
                </div>

                <div class="field is-grouped m-t-lg">
                    <div class="control">
                        <input type="submit" class="button p-l-xl p-r-xl is-link" value="Update" />
                    </div>
                    <div class="control">
                        <button class="button p-l-lg p-r-lg is-dark" onclick="clearLoginForm();">Clear</button>
                    </div>
                </div>


            </div>
        </div>

    </form>
    </div>
    {% endif %}

{% endblock %}

Final App/src/templates/user/register.html
{% extends "../base_generic.html" %}

{% block title-main %}Register{% endblock %}


{% block page-content %}
    {% load static %}
    <script src="{% static 'js/user.js' %}" defer></script>
    
  <div class="">
    <form id="register-form" method="post" action="{% url 'user:register' %}" class="box center-h p-lg" style="max-width: 700px;">
        {% csrf_token %}

        <div class="field title is-4 has-text-centered p-md">
            New User Registration
        </div>

        <p class="has-text-centered m-t-md m-b-lg">
            <i class="fas fa-user-plus is-size-3"></i>
        </p>

        <div class="columns m-t-md">
            <div class="column is-half">
                <div class="field">
                    <label class="label">First Name</label>
                    <div class="control">
                        <input type="text" class="input" name="first_name" placeholder="John" required />
                    </div>
                </div>

                <div class="field">
                    <label class="label">Last Name</label>
                    <div class="control">
                        <input type="text" class="input" name="last_name" placeholder="Doe" required />
                    </div>
                </div>
                
                <div class="field">
                    <label class="label">Bio</label>
                    <div class="control">
                        <textarea class="input" name="bio" style="resize: vertical; min-height: 115px; max-height: 200px;"></textarea>
                    </div>
                </div>

                <div class="field">
                    <label class="label">Set Availability</label>
                    <div class="help">Are you currently available to provide services?</div>
                    
                    <input type="radio" name="available" value="1" required /> Yes
                    <input type="radio" name="available" value="0" class="m-l-md" required checked /> No
                </div>

            </div>

            <div class="column is-half">
                <div class="field">
                    <label class="label">Phone</label>
                    <div class="control">
                        <input type="tel" class="input" name="phone" placeholder="+7 (928) 9387 8219" />
                    </div>
                </div>

                <div class="field">
                    <label class="label">Address</label>
                    <div class="control">
                        <input type="text" class="input" name="address" placeholder="Universitetskaya St 1, Innopolis, Tatarstan" />
                    </div>
                </div>

                <div class="field">
                    <label class="label">Email</label>
                    <div class="control">
                        <input type="email" class="input" name="username" placeholder="you@example.com" required />
                    </div>
                </div>

                <div class="field">
                    <label class="label">Password</label>
                    <div class="control">
                        <input type="password" class="input" name="confirm_password" required />
                    </div>
                </div>

                <div class="field">
                    <label class="label">Confirm Password</label>
                    <div class="control">
                        <input type="password" class="input" name="password" required />
                    </div>
                </div>

                <div class="field is-grouped m-t-lg">
                    <div class="control">
                        <input type="submit" class="button p-l-xl p-r-xl is-link" value="Register" />
                    </div>
                    <div class="control">
                        <button class="button p-l-lg p-r-lg is-dark" onclick="clearLoginForm();">Clear</button>
                    </div>
                </div>


            </div>
        </div>

    </form>
  </div>
{% endblock %}