Final App/src/main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView
from . import views

app_name = 'main'
urlpatterns = [
    #path('', views.index, name='index'),
    path('', RedirectView.as_view(url='/service/', permanent=True), name="index"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('service/', include('service.urls')),
    path('settings/', views.settings, name='settings'),
    path('notifications/', views.get_notifications, name='notifications'),
    path('notifications/<int:notif_id>/read', views.mark_notification_read, name='read-notification'), 
    path('notifications/all/read', views.markall_notification_read, name='read-notification-all'),
] 

Final App/src/service/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'service'  # SET THE NAMESPACE!
urlpatterns = [
    path('', views.index, name='index'),
    path('explore/', views.explore, name='explore'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('detail/<int:post_id>', views.detail, name='detail'),
    path('update/<int:post_id>', views.update, name='update'),
    path('close/<int:post_id>', views.close, name='close'), 
    path('delete/<int:post_id>', views.delete, name='delete'),

    path('<int:post_id>/comment/create/', views.create_comment, name='create-comment'),
]

Final App/src/user/urls.py
from django.urls import path
from . import views

app_name = 'user'  # SET THE NAMESPACE!
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('info/', views.info, name='info'),
    path('activity/', views.activity, name='activity'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_id>', views.data, name='data'),    
]

crse/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from crossservice import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^cross/', include('crossservice.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

Final App/src/main/models.py
from django.db import models

Final App/src/user/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

class Profile(models.Model):
    class Meta:
        app_label = 'user'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    bio = models.TextField(max_length=200, blank=True)

    phone = models.CharField(max_length=20, help_text='Enter phone number.')
    address = models.CharField(max_length=100, help_text='Enter address.')

    available = models.BooleanField(default=False)

    def email(self):
        return self.user.username
        
    def __str__(self):
        return self.user.username

Final App/src/main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, Http404

from django.urls import reverse
from django.contrib import auth, messages

from service.models import Notification

@login_required
def settings(request):
    return render(request, 'main/settings.html', context={
        'navigation': 'settings',
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })

@login_required
def get_notifications(request):
    
    try:
        notifications = Notification.objects.filter(
            owner=request.user
        ).order_by('-created_datetime')
    except Notification.DoesNotExist:
        notifications = []

    return render(request, 'main/notifications.html', context={
        'navigation': 'notifications',
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count(),
        'notifications': notifications,
    })


@login_required
def mark_notification_read(request, notif_id):
    try:
        notification = Notification.objects.filter(
            pk=notif_id
        )
    except Notification.DoesNotExist:
        raise Http404('Notification does not exist!')
    
    notification.is_read = True
    notification.save()

    messages.success(request, "Notification marked read!" , extra_tags='message-head info')
    messages.success(request, "You've successfully marked a notification as read.", extra_tags="message-body")

    return HttpResponseRedirect(reverse('notifications'))


@login_required
def markall_notification_read(request):
    try:
        unread = Notification.objects.filter(
            is_read=False
        )
    except Notification.DoesNotExist:
        raise Http404('Notification does not exist!')
    
    for notification in unread:
        notification.is_read = True
        notification.save()
    
    messages.success(request, "All unread notifications marked read!" , extra_tags='message-head info')
    messages.success(request, "You've successfully marked all unread notifications as read.", extra_tags="message-body")

    return HttpResponseRedirect(reverse('notifications'))

    

Final App/src/service/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse

from django.contrib import messages
import datetime

from django.db.models import Q
from .models import *


@login_required
def index(request):
    service_posts = ServicePost.objects.filter().order_by('-created_datetime')[:10]
    
    return render(request, 'service/index.html', {
        'navigation': 'service',
        'service_posts': service_posts,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })


@login_required
def explore(request):
    service_posts = ServicePost.objects.filter().order_by('-created_datetime')
    return render(request, 'service/explore.html', {
        'navigation': 'service',
        'service_posts': service_posts,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })        


@login_required
def search(request):
    
    if request.method == 'GET':
        search_text = request.GET.get('service_search_text')

        title_matches = ServicePost.objects.filter(
            Q(title__icontains=search_text) | Q(service__name__icontains=search_text)
        )

        description_matches = ServicePost.objects.filter(
            Q(description__icontains=search_text) | Q(service__info__icontains=search_text)
        )

        location_matches = ServicePost.objects.filter(
            Q(service__location__icontains=search_text)
        )

        tag_matches = ServicePost.objects.filter(
            
        ).filter(service__tags__label__icontains=search_text)
         

    return render(request, 'service/search.html', {
        'search_text': search_text,
        'navigation': 'service',
        'title_matches': title_matches,
        'description_matches': description_matches,
        'location_matches': location_matches,
        'tag_matches': tag_matches,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })


@login_required
def create(request):
    if request.method == 'POST':
        # Creating new service and saving it
        new_service = Service()
        new_service.name = request.POST.get('service-name')
        new_service.info = request.POST.get('service-description')
        new_service.start_datetime = request.POST.get('service-start-datetime')
        new_service.end_datetime = request.POST.get('service-end-datetime')
        new_service.location = request.POST.get('service-location')
        
        new_service.save() 
        tags = request.POST.getlist('service-tags')
        for tag_name in tags:
            tag, created = Tag.objects.get_or_create(
                label = tag_name
            )
            
            new_service.tags.add(tag)
        
        new_service.save()

        # Creating new service post record and saving it
        new_post = ServicePost()
        new_post.title = request.POST.get('post-title')
        new_post.description= request.POST.get('post-description')
        new_post.is_request_post = (request.POST['is_request_post'] == '1')
        new_post.owner = User.objects.get(username=request.user.username)
        new_post.created_datetime = datetime.datetime.now()
        new_post.service = new_service
        
        new_post.save()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You created a new service post titled '" + request.POST.get('post-title') + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post Published!", extra_tags='message-head')
        
        messages.success(request, 'Hey ' + request.user.first_name + '! We have recorded and published your post!', extra_tags="message-body")
        
        return HttpResponseRedirect(reverse('service:create'))
    
    return render(request, 'service/create.html', {
        'navigation': 'service',
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })
    
@login_required
def detail(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
        comments = ServicePostComment.objects.filter(post=post).order_by('-created_datetime')

    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    return render(request, 'service/details.html', {
        'navigation': 'service',
        'post': post,
        'comments': comments,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })


@login_required
def update(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.method == 'POST':
        
        post.service.name = request.POST.get('service-name')
        post.service.info = request.POST.get('service-description')
        post.service.start_datetime = request.POST.get('service-start-datetime')
        post.service.end_datetime = request.POST.get('service-end-datetime')
        post.service.location = request.POST.get('service-location')
        
        post.service.save()
        post.save()

        post.service.tags.clear()
        tags = request.POST.getlist('service-tags')
        for tag_name in tags:
            tag, created = Tag.objects.get_or_create(
                label = tag_name
            )
            
            post.service.tags.add(tag)
        
        post.service.save()
        post.save()

        post.title = request.POST.get('post-title')
        post.description= request.POST.get('post-description')
        post.is_request_post = (request.POST['is_request_post'] == '1')
        post.modified_datetime = datetime.datetime.now()
        
        post.save()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You updated your service post information. The post is titled '" + request.POST.get('post-title') + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post Updated!", extra_tags='message-head')
        
        messages.success(request, 'Hey ' + request.user.first_name + '! We have updated your post!', extra_tags="message-body")
        
        return HttpResponseRedirect(reverse('service:update', kwargs={'post_id': post.id})) 
    
    return render(request, 'service/update.html', {
        'navigation': 'service',
        'post': post,
        'unread_notifications_count': Notification.objects.filter(is_read=False,owner=request.user).count()
    })

@login_required
def close(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.user != post.owner:
        messages.warning(request, "Unauthorized Attempt", extra_tags='message-head')
        messages.warning(request, "You're not authorized to perform this operation. Only the post owner can close the post.", extra_tags='message-body')

    else:
        post.closed_datetime = datetime.datetime.now()
        post.save()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You recently closed a service post titled '" + post.title + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post closed", extra_tags='message-head info')
        messages.warning(request, "You've recently closed a service post. You will no require receive comments in that post, although the post is still visible unless you delete it!", extra_tags='message-body')

    return HttpResponseRedirect(reverse('service:detail', kwargs={'post_id': post.id}))


@login_required
def delete(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.user != post.owner:
        messages.warning(request, "Unauthorized Attempt", extra_tags='message-head error')
        messages.warning(request, "You're not authorized to perform this operation. Only the post owner can delete the post.", extra_tags='message-body')

    else:
        post.service.delete()
        post.delete()

        notification = Notification()
        notification.owner = request.user
        notification.created_datetime = datetime.datetime.now()
        notification.text = "You deleted your service post titled '" + post.title + "'"
        notification.target_url = ""
        notification.save()

        messages.success(request, "Post Deleted", extra_tags='message-head info')
        messages.warning(request, "You've successfully deleted a service post. You will no longer be able to access the post!", extra_tags='message-body')

    return HttpResponseRedirect(reverse('service:index'))


@login_required
def create_comment(request, post_id):
    try:
        post = ServicePost.objects.get(pk=post_id)
    except ServicePost.DoesNotExist:
        raise Http404('Post does not exist')
    
    if request.method == 'POST':
        comment_text = request.POST.get('comment')
        
        new_comment = ServicePostComment()
        new_comment.text = comment_text
        new_comment.created_datetime = datetime.datetime.now()

        new_comment.owner = request.user
        new_comment.post = post

        new_comment.is_private = False
        if request.POST.get('is-private'):

Final App/src/templates/service/details.html
{% extends "../base_generic.html" %}

{% block title-main %}{{ post.title }}{% endblock %}

{% block page-content %}
    {% load static %}
    <script src="{% static 'js/service.js' %}"></script>

    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li>
                <a href="{% url 'service:explore' %}">
                    <span>Services</span>
                </a>
            </li>
            
            <li class="is-active" style="">
                <a style="" href="{{ post.get_absolute_url }}">
                    <span>{{ post.title }}</span>
                </a>
            </li>
        </ul>
    </nav>

    {% if user == post.owner %}
    <div class="columns p-sm">
        <div class="column">
            <a class="is-link" href="{% url 'service:update' post.id %}">Update Post</a>
        </div>
        <div class="column has-addons has-text-right">
            {% if post.closed_datetime is None %}
            <span class="tag has-textweight-bold">Is Currently Open.</span>
            <a class="tag button is-link" href="{% url 'service:close' post.id %}">
                Close?
            </a>
            {% endif %}
            &nbsp;&nbsp;
            <span class="button tag is-danger">Delete?</span>
        </div>
    </div>
    {% endif %}

    <div class="box" style="position: relative;">
        <div class="title is-4" style="max-height:35px;">
            {{ post.title }}
        </div>
        
        <div class="has-text-white tag has-text-centered has-text-weight-semibold" style="position: absolute; top: 12px; right: -15px; transform: rotate(45deg); background-color: {% if post.is_request_post %}#2366d1{% else %}#00b89c{% endif %}; width: 80px; letter-spacing:1px;" title="Whether the service is being requested or offered!">
            {% if post.is_request_post %}
                REQUEST
            {% else %}
                OFFERING
            {% endif %}
                        
        </div>

        <div class="level is-mobile">
            <div class="level-left"></div>
            
            <div class="level-right">
                <div class="level-item" style="overflow: hidden;white-space: nowrap; text-overflow: ellipsis;">
                    <span title="Last modified on {{ post.modified_datetime }}">
                        <span class="icon is-size-6">
                            <i class="fas fa-calendar-check"></i>
                        </span> {{ post.created_datetime }}
                    </span>
                </div>

                <div class="level-item" style="overflow: hidden;white-space: nowrap; text-overflow: ellipsis;">
                    <span title="Posted by {{ post.owner.first_name }} {{ post.owner.last_name }}">
                        <span class="icon">
                            <i class="fas fa-user"></i>
                        </span>
                        
                        <a class="is-link" href="javascript:void(0)" onclick="showUserData({{ post.owner.id }})">{{ post.owner.first_name }} {{ post.owner.last_name }}</a>
                    </span>
                </div>
            </div>
        </div>

        <div class="subtitle is-6 p-t-sm">
            {{ post.description }}
        </div>

        <div class="has-background-light p-md">
            

            <div class="title is-5 has-text-grey-dark">
                {{ post.service.name }}
            </div>

            <div class="subtitle is-6">
                {{ post.service.info }}
            </div>

            <div class="">
                <span class="has-text-weight-bold m-r-md">Period:</span> {{ post.service.start_datetime }}
                <span class="subtitle has-textweight-bold has-text-info m-l-lg m-r-lg">to</span>
                {{ post.service.end_datetime }}
            </div>

            <p class="m-t-md">
                <span class="has-text-weight-bold">Location</span>:
                {{ post.service.location }}
            </p>

            <div class="tags m-t-md">
                <span class="has-text-weight-bold m-r-md">Associated Tags:</span>
                
                {% for tag in post.service.tags.all %}
                    <span class="tag is-dark">
                        {{ tag }}
                    </span>
                {% endfor %}
                
            </div>

            

        </div>
    </div>

    <form method="POST" action="{% url 'service:create-comment' post.id %}">
    {% csrf_token %}
        
    <div class="field">
        <div class="control" style="position: relative;">
            <textarea class="textarea p-md" type="text" placeholder="Leave a comment here..." style="min-height: 110px; max-height: 180px; padding-bottom:60px!important; resize:vertical;" name="comment"></textarea>

            <div class="field has-addons" style="position: absolute; right: 18px; bottom:12px;">
                <div class="control has-background-light p-l-sm p-t-sm p-r-md">
                    <label class="checkbox">
                    <input type="checkbox" name="is-private" /> Private
                    </label>
                </div>
                <div class="control">
                    <input type="submit" class="button is-info" value="Comment" />
                </div>
            </div>
        </div>    
    </div>
    </form>

    <fieldset class="has-text-centered m-t-lg m-b-md" style="border-top: 1px solid #ccc;">
        <legend class="has-text-grey-darker p-l-md p-r-md is-size-4">Past Comments/Responses</legend>
    </fieldset>
    
    {% if comments.0 %}
        {% for comment in comments %}
        {% if not comment.is_private or comment.owner.id is request.user.id or post.owner.id is request.user.id %}
        <div class="card p-md m-b-md p-b-xxs">
            <div class="level p-b-md" style="margin-bottom: 0!important;">
                <a class="has-text-weight-semibold" href="javascript:void(0)" onclick="showUserData({{ comment.owner.id }});">
                    <span class="icon is-size-6">
                        <i class="fas fa-user"></i>
                    </span>
                    {{ comment.owner.first_name }} {{ comment.owner.last_name }}
                </a>
                <div class="level-right">
                    <div class="level-item">
                        {% if comment.is_private %}
                        <span class="icon is-size-6" title="This comment is private & visible to only selected users.">
                            <i class="fas fa-user-shield"></i>
                        </span>
                        {% else %}
                        <span class="icon is-size-6" title="This comment is public to all users.">
                            <i class="fas fa-users"></i>
                        </span>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="">
                <textarea class="textarea has-text-black-bis" style="min-height: 80px; max-height: 200px; resize: vertical; cursor: text;" disabled>{{ comment.text }}</textarea>
            </div>
            <div class="m-t-sm has-text-right has-text-grey-darker has-text-weight-bold">
                {{ comment.created_datetime }}
            </div>
        </div>
        {% endif %}
        {% endfor %}

    {% else %}
        <p class="subtitle is-5 has-text-centered">
            There are no comments so far for this post.
        </p>
    {% endif %}

{% endblock %}

Final App/src/templates/service/index.html
{% extends "../base_generic.html" %}

{% block title-main %}Services{% endblock %}

{% block page-content %}

    {% load static %}
    <script src="{% static 'js/service.js' %}"></script>

    <nav id="find-services_anchor" class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <span class="has-text-weight-semibold">Content</span>:
        <li><a href="#find-services_anchor">Find Services</a></li>
        <li><a href="#create-service-posts_anchor">Create Service Post</a></li>
        <li><a href="#my-service-posts_anchor">My Service Posts</a></li>
        <li class=""><a href="#recent-services_anchor" aria-current="page">Recent Service Posts</a></li>
    </ul>
    </nav>

    <form id="create-service-posts_anchor"  method="GET" action="{% url 'service:search' %}" class="box">
        <div class="title is-5">
            Finding Services you are looking for
            <a href="{% url 'service:explore' %}" class="is-link is-size-6 is-pulled-right">Explore All</a>
        </div>

        <div class="field has-addons">
            <div class="control has-icons-left is-expanded">
                <input type="search" name="service_search_text" class="input" placeholder="Type name, keywords, locations, tags, etc. to find matching service posts." />
                <span class="icon is-left">
                    <i class="fas fa-search"></i>
                </span>
            </div>
            
            <div class="control">
                <input type="submit" class="input button is-info" value="Search" />
            </div>
        </div>
    </form>

    <div id="my-service-posts_anchor"  class="box">
        <div class="title is-5">
            Creating Service Posts
        </div>
        <p >
            Didn't find what you're looking for?
            <a class="is-link" href="{% url 'service:create' %}">Create a new service post</a>
            requesting or offering a service.
        </p>
    </div>

    <div id="recent-services_anchor" class="box">
        <div class="title is-5">My Service Posts</div>
        <p>
            Your service posts are listed in your profile activity page.
            <a class="is-link" href="{% url 'user:activity' %}">Go to profile activity</a>.
        </p>
    </div>


    <div class="box has-background-grey-lighter m-t-xl">
        <div class="title is-4 has-text-grey-darker">Recently Published Posts
            <sup class="button is-pulled-right  is-size-6 "><a href="{% url 'service:explore' %}">Explore All</a></sup>
        </div>

        <div class="columns is-multiline">
        {% for post in service_posts %}
        <div class="box p-md is-rounded column m-t-md m-r-lg m-b-md m-l-lg" style="max-width: 360px; height: 324px; position: relative;">
                <div class="is-size-5" style="height: 66px; overflow: hidden;text-overflow: ellipsis;" title="{{ post.title }}">
                    {{ post.title }}
                </div>
                
                <div class="columns p-t-xs" style="max-height: 40px;">
                    <div class="has-text-white tag has-text-centered has-text-weight-semibold" style="position: absolute; top: 12px; right: -15px; transform: rotate(45deg); background-color: {% if post.is_request_post %}#2366d1{% else %}#00b89c{% endif %}; width: 80px; letter-spacing:1px;" title="Whether the service is being requested or offered!">
                        {% if post.is_request_post %}
                            REQUEST
                        {% else %}
                            OFFERING
                        {% endif %}
                        
                    </div>

                    <span class="column is-half" style="overflow: hidden;white-space: nowrap; text-overflow: ellipsis;" title="Posted on {{ post.created_datetime }}">
                        <span class="icon is-size-6">
                            <i class="fas fa-calendar-check"></i>
                        </span> {{ post.created_datetime }}
                    </span>

                    <span class="column is-half" style="overflow: hidden;white-space: nowrap; text-overflow: ellipsis;" title="Posted by {{ post.owner.first_name }} {{ post.owner.last_name }}">
                        <span class="icon">
                            <i class="fas fa-user"></i>
                        </span>
                        <a class="is-link" href="javascript:void(0)" onclick="showUserData({{ post.owner.id }})">{{ post.owner.first_name }} {{ post.owner.last_name }}</a>
                        
                    </span>
                </div>
                

                <div class="p-l-md p-t-sm p-r-md m-b-sm" style="height: 160px; border: 1px solid #ccc; overflow: hidden;white-space: nowrap; text-overflow: ellipsis;">
                    <div style="overflow: hidden;white-space: nowrap; text-overflow: ellipsis;" title="{{ post.service.name }}">
                        <span class="has-text-weight-semibold">Service</span>:
                        <a href="{{ post.get_absolute_url }}" class="has-text-weight-bold has-text-gray">{{ post.service.name }}</a>
                    </div>
                    <div style="height: 40px; overflow: hidden;white-space: nowrap; text-overflow: ellipsis;" title="{{ post.service.info }}">
                        {{ post.service.info }}
                    </div>

                    <div title="Service since {{ post.service.start_datetime }}">
                        <span class="has-text-weight-semibold"> From</span>: {{ post.service.start_datetime }}
                    </div>
                    
                    <div title="Service till {{ post.service.end_datetime }}">
                        <span class="has-text-weight-semibold"> To</span>: {{ post.service.end_datetime }}
                    </div>

                    <div class="tags m-t-xs" style="height: 30px; overflow: hidden;white-space: nowrap; text-overflow: ellipsis;" title="TAGS: {%for tag in post.service.tags.all %}{{tag}}, {% endfor %}">
                        {% for tag in post.service.tags.all %}
                        <span class="tag is-dark">
                            {{ tag }}
                        </span>
                        {% endfor %}
                    </div>

                </div>

                <div class=" has-text-centered">
                    <a href="{{ post.get_absolute_url }}">View Details & Respond</a>
                </div>

            </div>
        {% endfor %}
        </div>
    </div>

    
{% endblock %}